config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "home/about" => "homes#about", as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 has_one_attached :image
 belongs_to :user

 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { in: 2..20 } ,uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


 # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
   # flash[:notice] = "Signed in successfully"
    user_path(resource)
  end

 # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully"
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

    # 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
     flash[:notice] = "Book was successfully created"
     # 4. index画面へリダイレクト
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully"
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body, :introduction, :profile_image)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @user = User.new
    @users = User.all
    @userss=current_user
  end

  def show
    @user = User.find(params[:id])
    @books=@user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully"
     redirect_to user_path(@user.id)
    else
      @users = User.all
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user.id)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container">
<div class="row">

<div class="col-md-3">
  <h2>User info</h2>
  <p><%= image_tag user.get_profile_image(100,100) %></p>

  <!-- ユーザーの詳細 -->
  <div class="profile-container">

   <h6>name <%= user.name %></h6>
	  <h6>introduction <%= user.introduction %></h6>

  <div class="btn btn-outline-secondary btn-block">
  <p><%= link_to edit_user_path(user) do %></p>
  　<i class="fas fa-user-cog "></i>
   <% end %>
 </div>

<h2>New book</h2>

<%= form_with model: book do |f| %>
 <p>Title</p>
 <%= f.text_field :title %>

 <p>Opinion</p>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' ,class:'nav-link text-light'%>
<% end %>
 </div>
</div>

app/views/books/edit.html.erb
<% if flash[:notice] %>
<p id="notice">
  <%= flash[:notice] %>
</p>
<% end %>

 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

<h1>Editing Book</h1>
<%= form_with model: @book, url: book_path(@book.id) do |f| %>

<table>
<tr>
<div class="field">
<label for="book_title">Title</label>
</tr>
<tr>
  <%= f.text_field :title %>
</div>
</tr>

<tr>
<div class="field">
<label for="book_body">Opinion</label>
<tr>
<tr>
  <%= f.text_area :body %>
</div>
</tr>
</table>

<div class="field">
  <%= f.submit 'Update Book', class:'btn btn-success' %>
</div>
<% end %>

<table>
<tr>
<td><%= link_to "Show", book_path(@book.id) %></td>
<td><p>|</p></td>
<td><%= link_to "Back", books_path %></td>
</tr>
</table>

app/views/books/index.html.erb
<div class="container">
  <% if @book.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= @book.errors.count %>errors prohibited this obj from being saved:
    </h6>
      <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
 <% end %>
<div class="row">



<div class="col-md-3">

  <h2>User info</h2>
  <p><%= image_tag @user.get_profile_image(100,100) %></p>

  <!-- ユーザーの詳細 -->
  <div class="profile-container">

   <h6>name <%= @user.name %></h6>
	 <h6>introduction <%= @user.introduction %></h6>

  <div class="btn btn-outline-secondary btn-block">
  <p><%= link_to edit_user_path(@user) do %></p>
  　<i class="fas fa-user-cog "></i>
   <% end %>
 </div>

<h2>New book</h2>

<%= form_with model: @book do |f| %>
 <p>Title</p>
 <%= f.text_field :title %>

 <p>Opinion</p>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' ,class:'nav-link text-light'%>
<% end %>
 </div>
</div>

<div class="col-md-8 offset-md-1">
  	<h2>Books</h2>
  	<table>
    <thead>
     <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
     <tr>
      <td>
        <%= link_to user_path(book.user) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>

      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
     </tbody>
    </table>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= flash[:notice] %>

<%= render 'books/list', {book: @books, user: @book.user} %>

 <% if @book.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= @book.errors.count %>errors prohibited this obj from being saved:
    </h6>
      <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
 <% end %>

<body>
 <div class="col-md-8 offset-md-1">
  	<h2>Book detail</h2>
  	<table>
    <thead>
     <tr>

      <th colspan="3"></th>
     </tr>
    </thead>

 <tbody>
 <tr>
   <td><%= image_tag @book.user.get_profile_image(100,100) %></td>
   <td><%= link_to @book.user.name, user_path(@book.user.id) %></td>
   <td><%= link_to @book.title, book_path(@book.id) %></td>
   <td><%= @book.body %></td>

   <% if user_signed_in? && current_user.id == @book.user_id %>
    <td><%= link_to "Edit", edit_book_path(@book.id), class:'btn btn-sm btn-success' %></td>
   <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" , class:'btn btn-sm btn-danger' %></td>
   <% end %>


 </tr>
</tbody>
</table>
</body>

 </div>
 </div>
 </div>

app/views/homes/about.html.erb
<p id="notice"></p>
      <div class="container">
      <div class="row">
      <h1 class="px-3 mx-auto">Welcome to
      <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<p id="notice"></p>
      <div class="container">
      <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>  !!</h1>

      <P>In
      <i class="fas fa-book"></i>
      <strong>Bookers,</strong>
      </P>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="row">
        <%= link_to "Log in", new_user_session_path, class:'btn btn-info btn-sm btn-block mb-3' %>
      </div>

      <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class:'btn btn-success btn-sm btn-block' %>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    	<!-- FontAwesomeの読み込み -->
	<link href="./font-awesome.css" rel="stylesheet">
  </head>

  <body>
     <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container">
           <a class ="navbar-brand" href="/">
             <span>Bookers</span>
           </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
      <li class="nav-item">
       <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to "/users", class:"nav-link text-light" do %>
        <i class="fas fa-users"></i>Users
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to  "/books", class:"nav-link text-light" do %>
        <i class="fas fa-book-open"></i>Books
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i>Log out
        <% end %>
      </li>
      <% else %>

       <li class="nav-item">
       <%= link_to root_path, class:"nav-link text-light" do %>
     <i class="fas fa-home"></i>Home
      <% end %>
      </li>

      <li class="nav-item">
        <%= link_to about_path, class:'nav-link text-light' do %>
        <i class="fas fa-link"></i>About
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to  new_user_registration_path, class:'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_session_path, class:'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
        <% end %>

          </ul>
         </div>
         </div>
       </nav>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer>
     <div class="container mt-5">
  	 <div class="row">
     <div class="mx-auto">
    	<p>CopyRight Infratop.inc</p>
     </div>
     </div>
     </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<h2>Users Info</h2>
<%= form_with model: @user, url: user_path(@user.id) do |f| %>

 <% if @user.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= @user.errors.count %>errors prohibited this obj from being saved:
    </h6>
      <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
 <% end %>

<table>
<tr>
<div class="field">
<label for="user_title">Name</label>
</tr>
<tr>
  <%= f.text_field :name %>
</div>
</tr>

<tr>
<div class="field">
<label for="user_image">Image</label>
</tr>
<tr>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
</div>
</tr>

<tr>
<div class="field">
<label for="user_body">Introduction</label>
<tr>
<tr>
  <%= f.text_area :introduction %>
</div>
</tr>
</table>

<div class="field">
  <%= f.submit 'Update User', class:'btn btn-secondary' %>
</div>
<% end %>

app/views/users/index.html.erb
<div class="container">
<div class="row">

<div class="col-md-3">
  <h2>User info</h2>
  <p><%= image_tag @userss.get_profile_image(100,100) %></p>

  <!-- ユーザーの詳細 -->
  <div class="profile-container">

   <h6>name <%= @userss.name %></h6>
	  <h6>introduction <%= @userss.introduction %></h6>

  <div class="btn btn-outline-secondary btn-block">
  <p><%= link_to edit_user_path (@userss) do %></p>
  　<i class="fas fa-user-cog "></i>
   <% end %>
 </div>

<h2>New book</h2>

<%= form_with model: @book do |f| %>
 <p>Title</p>
 <%= f.text_field :title %>

 <p>Opinion</p>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' ,class:'nav-link text-light'%>
<% end %>
 </div>
</div>

<div class="col-md-8 offset-md-1">
  	<h2>Users</h2>
  	<table>
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
    </thead>

     <tbody>
      <% @users.each do |user| %>
     <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
     <% end %>
     </tbody>

    </table>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container">
<div class="row">

<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="col-md-3">
  <h2>User info</h2>
  <p><%= image_tag @user.get_profile_image(100,100) %></p>

  <!-- ユーザーの詳細 -->
  <div class="profile-container">

   <h6>name <%= @user.name %></h6>
	  <h6>introduction <%= @user.introduction %></h6>

  <div class="btn btn-outline-secondary btn-block">
  <p><%= link_to edit_user_path(@user) do %></p>
  　<i class="fas fa-user-cog "></i>
   <% end %>
 </div>

<h2>New book</h2>

<%= form_with model: @book do |f| %>
 <p>Title</p>
 <%= f.text_field :title %>

 <p>Opinion</p>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' ,class:'nav-link text-light'%>
<% end %>
 </div>
</div>

 <div class="col-md-8 offset-md-1">
  	<h2>Books</h2>
  	<table>
    <thead>
     <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>

 <tbody>
 <% @books.each do |book| %>
 <tr>
   <td>
     <%= link_to user_path(book.user) do %>
     <%= image_tag book.user.get_profile_image(100,100) %>
     <% end %>
   </td>
   <td><%= link_to book.title, book_path(book.id) %></td>
   <td><%= book.body %></td>
 </tr>
 <% end %>
</tbody>
</table>

 </div>
 </div>
 </div>